Solutions to problems 2.4 and 2.5
alberto-chiarini/Problems-in-measure-theory pull request #1
Opened 2020-09-12 16:26 UTC by adrien-castella

2020-09-13 11:01 UTC, alberto-chiarini requested changes
Hi Adrien, thanks for the problems. Only one comment for 2.4 though, for a sigma algebra you don't need the third condition as it follows always from closure under countable union and complementation.

2020-09-13 13:51 UTC, adrien-castella commented
Alright, I will remove that part of the proof and commit it right away.

2020-09-13 14:29 UTC, adrien-castella commented
I have added exercises 2.2 and 2.14 into the file as well.

2020-09-14 08:09 UTC, alberto-chiarini approved these changes

2020-09-14 08:09 UTC, merged